services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./config.js:/usr/app/config.js

  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - db_data:/data/db

volumes:
  db_data:
